site_name: Csb's Blog

theme:
  name: material
  favicon: https://s2.loli.net/2024/04/26/PmRdM9iGnvOJHgu.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: SteelBlue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    - content.code.copy
  language: zh
  icon:
    repo: fontawesome/brands/github

edit_uri: edit/main/docs
repo_url: https://github.com/Somer2005/csb.github.io
repo_name: csb.github.io

nav:
  - 导言页: index.md
  - 项目笔记:
      - 特殊篇——git的基础使用: project/git.md
      - 搜广推项目——阿里移动推荐: project/project1.md
  - 算法笔记:
      - 线性规划:
        - 基础: algorithm/OperationResearch/LinearProgramming.md
        - 线性规划的花活: algorithm/OperationResearch/LinearProgramming2.md
      - 运输问题: algorithm/OperationResearch/TransportationModel.md
      - 目标规划: algorithm/OperationResearch/GoalPlanning.md
      - 整数规划: algorithm/OperationResearch/IntegerProgramming.md
      - 网络计划: algorithm/OperationResearch/NetworkPlanning.md
      - 存储论: algorithm/OperationResearch/Store.md
      - 博弈论: algorithm/OperationResearch/GameTheory.md
      - 对策分析: algorithm/OperationResearch/PlanAnalysis.md

      - 哈希表笔记: algorithm/hashtable.md
  - 英语笔记:
      - IELTS作文的三个万能论据: project/IELTSWriting.md
  - 公开课笔记:
      - MIT6.824: MIT6.824/Mapreduce.md
  - 一生一芯笔记:
      - PA系列: ysyx/PA0.md
      - F3 数电: ysyx/electric.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/custom.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
